In [2]:
import numpy as np
from numpy.random import randint as ri

## Reshaping 

In [6]:

a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)


print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)



Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [9]:
a = np.arange(6).reshape((3, 2))

In [10]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
np.reshape(a, (-1, 3)) # the unspecified value is inferred to be 2

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
a.shape = 2,3
a.shape = 1,6
a.shape = 3,-1

(3, 2)

## indexing and slicing

#### vector indexing

In [87]:
arr = np.arange(0,11)
print("Array:",arr)


print("Element 7th index is:", arr[7])


print("Elements from 3rd to 5th index are:", arr[3:6])


print("Elements up to 4th index are:", arr[:4])


print("Elements from last backwards are:", arr[::-1])


print("3 Elements from last backwards are:", arr[-1:-6:-2]) # Output[10  8  6]


arr = np.arange(0,21,2)
print("New array:",arr)


print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


#### matrix indexing 

In [11]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])


print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")


print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
--------------------------------
 [[33 98 11 67 14]
 [86 48 46 74 95]
 [79 13 47 99 59]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 46

Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 46

Row or column extract
----------------------
Entire row at index 2: [79 13 47 99 59]
Entire column at index 3: [67 74 99]

Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[74 95]
 [99 59]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[98 67]
 [48 74]]


## Fancy indexing and index trick
NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

#### Indexing with Arrays of Indices

In [8]:
a = np.arange(12)**2                       # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
a[i]                                       # the elements of a at the positions i

array([ 1,  1,  9, 64, 25], dtype=int32)

In [9]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
a[j]                                       # the same shape as j

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [4]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
i = np.array( [ [0,1],                        # indices for the first dim of a
                [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                [3,3] ] )

a[i,j]                                        # i and j must have equal shape

array([[ 2,  5],
       [ 7, 11]])

In [ ]:
a[i,2]

In [11]:
a[:,j]                                     # i.e., a[ : , j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

Naturally, we can put i and j in a sequence (say a list) and then do the indexing with the list.

In [12]:
l = [i,j]
a[l]                                       # equivalent to a[i,j]

array([[ 2,  5],
       [ 7, 11]])

However, we can not do this by putting i and j into an array, because this array will be interpreted as indexing the first dimension of a.

In [7]:
s = np.array( [i,j] )
s# not what we want

array([[[0, 1],
        [1, 2]],

       [[2, 1],
        [3, 3]]])

In [14]:
a[tuple(s)]                                # same as a[i,j]

array([[ 2,  5],
       [ 7, 11]])

#### Application : 

common use of indexing with arrays is the search of the maximum value of time-dependent series:

In [10]:
time = np.linspace(20, 145, 5)                 # time scale
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [16]:
data = np.sin(np.arange(20)).reshape(5,4)      # 4 time-dependent series
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [20]:
ind = data.argmax(axis=0)                  # index of the maxima for each series
ind

array([2, 0, 3, 1])

In [21]:
time_max = time[ind]                       # times corresponding to the maxima
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [27]:
data_max = data[[2, 0, 3, 1],list(range(data.shape[1]))] # => data[[2, 0, 3, 1],[0, 1, 2, 3]]
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [28]:
np.all(data_max == data.max(axis=0))

True

You can also use indexing with arrays as a target to assign to:

In [30]:
a = np.arange(5)

a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

### Indexing with Boolean Arrays

When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t.

The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array:

In [32]:
a = np.arange(12).reshape(3,4)
b = a > 4
b                                          # b is a boolean with a's shape

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
a[b]                                       # 1d array with the selected elements

array([ 5,  6,  7,  8,  9, 10, 11])

This property can be very useful in assignments:

In [34]:
a[b] = 0                                   # All elements of 'a' higher than 4 become 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

## slicing and Subetting 

In [12]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")

mat_slice[0,0] = 1000
print (mat_slice)

print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]

Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


## Updating  arrays
* insert 
* append
* delete

In [19]:
x = np.arange(4.0).reshape(2, 2)
x

array([[0., 1.],
       [2., 3.]])

In [20]:
np.insert(x, 1, 5)

array([0., 5., 1., 2., 3.])

In [21]:
np.insert(x, 1, 5, axis=0)

array([[0., 1.],
       [5., 5.],
       [2., 3.]])

In [22]:
np.insert(x, 1, 5, axis=1)

array([[0., 5., 1.],
       [2., 5., 3.]])

In [23]:
y = np.arange(16.0)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [24]:
np.insert(y, [2], [5, 6])

array([ 0.,  1.,  5.,  6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,
       11., 12., 13., 14., 15.])

In [25]:
np.insert(y, slice(2, 4), [5, 6])

array([ 0.,  1.,  5.,  2.,  6.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,
       11., 12., 13., 14., 15.])

In [57]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.delete(x, 1, 0)

In [ ]:
np.delete(x, np.s_[::2], 1)

In [ ]:
np.delete(x, [1,3,5], None)

## Broadcasting 

NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
In the simplest case, the two arrays must have exactly the same shape.
NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
dimensions, and works its way forward. Two dimensions are compatible when
they are equal, or one of them is 1

In [14]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [16]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [35]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [18]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [19]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+add_scalar)

[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


## diagonal operations 

In [7]:
x = np.arange(9).reshape((3,3))

x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.diag(x)

array([0, 4, 8])

In [10]:
np.diag(x, k=1)

array([1, 5])

In [11]:
np.diag(x, k=-1)

array([3, 7])

In [12]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [13]:
#Create a two-dimensional array with the flattened input as a diagonal.

np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [15]:
#An array with ones at and below the given diagonal and zeros elsewhere.

np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [16]:
np.tri(3, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [17]:
#return a Lower triangle of an array.

np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [18]:
#return Upper triangle of an array.

np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

## Axis transformations

In [20]:

print(x)
print('1d')
print(np.atleast_1d(x))
print('2d')
print(np.atleast_2d(x))
print('3d')
print(np.atleast_3d(x))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1d
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2d
[[0 1 2]
 [3 4 5]
 [6 7 8]]
3d
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]


#### 

In [46]:
x = np.array([1,2])
x.ndim

1

In [48]:
x[np.newaxis,:]

array([[1, 2]])

In [43]:
y = x[:,np.newaxis]  # Equivalent to x[:,np.newaxis]


array([[1],
       [2]])

In [55]:
y = np.expand_dims(x, axis=0)

y.shape

(1, 2)

In [57]:
y = np.expand_dims(x, axis=1)  # Equivalent to x[:,np.newaxis]
y

array([[1],
       [2]])

## Merging arrays


In [63]:
a = np.floor(10*np.random.random((2,2)))
print(a)


b = np.floor(10*np.random.random((2,2)))
print(b)

print(np.vstack((a,b)))  #Stacks arrays in sequence vertically (row wise)

print(np.hstack((a,b))) #Stacks arrays in sequence horizontally (column wise)


[[0. 9.]
 [0. 8.]]
[[4. 2.]
 [6. 4.]]
[[0. 9.]
 [0. 8.]
 [4. 2.]
 [6. 4.]]
[[0. 9. 4. 2.]
 [0. 8. 6. 4.]]


In [67]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

## split arrays

In [71]:
a = np.floor(10*np.random.random((2,12)))

np.hsplit(a,3)   # Split a into 3

np.hsplit(a,(3,4))   # Split a after the third and the fourth column



[array([[3., 4., 3.],
        [2., 3., 5.]]), array([[9.],
        [8.]]), array([[8., 1., 5., 4., 1., 6., 0., 7.],
        [3., 2., 1., 5., 3., 0., 4., 3.]])]

## Copies and Views

### No Copy at All

In [66]:
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [67]:
b.shape = 3,4    # changes the shape of a
a.shape

(3, 4)

In [30]:
def f(x):
    print(id(x))

id(a)                           # id is a unique identifier of an object

f(a)

140547996269344


#### View or Shallow Copy

Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [68]:
c = a.view()
c is a

False

In [69]:
c.base is a                        # c is a view of the data owned by a

True

In [70]:
c.flags.owndata

False

In [71]:
c.shape = 2,6                      # a's shape doesn't change
a.shape

(3, 4)

In [72]:
c[0,4] = 1234                      # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [31]:
# Slicing an array returns a view of it:

s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] 

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

## Deep Copy

The copy method makes a complete copy of the array and its data.

In [32]:
d = a.copy()                          # a new array object with new data is created
d is a

d.base is a                           # d doesn't share anything with a

d[0,0] = 9999
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

## Manipulations
### array splitting 
array_split , dsplit , hsplit , vsplit

### array merging 
column_stack, concatenate,  dstack, hstack, tile , repeat,  vstack

### axis transormation 
newaxis , ravel , reshape, resize, squeeze, swapaxes, take, transpose

### miscellaneous
diagonal , ndarray.item

## all, any, nonzero, where
### nonzero : Return the indices of the elements that are non-zero.





In [ ]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]])
np.nonzero(x)

### where: Return elements, either depending on condition

In [26]:
x = np.arange(9).reshape(3, 3)
np.where( x > 5 )

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

## Ordering
argmax, argmin, 
argsort, max, min, sort

In [75]:
### sort

a = np.array([[1,4],[3,1]])
print(a)
np.sort(a)                # sort along the last axis

print(np.sort(a, axis=None) )    # sort the flattened array

print(np.sort(a, axis=0) )       # sort along the first axis


[[1 4]
 [3 1]]
[1 1 3 4]
[[1 1]
 [3 4]]


__argsort__ : Returns the indices that would sort an array.

In [ ]:
x = np.array([3, 1, 2])
np.argsort(x)

* Two-dimensional array:

In [36]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [37]:
np.argsort(x, axis=0)  # sorts along first axis (down)

array([[0, 1],
       [1, 0]])

In [38]:
np.argsort(x, axis=1)  # sorts along last axis (across)

array([[0, 1],
       [0, 1]])

__max__ : 

In [79]:
a = np.arange(6).reshape(2,3)
print(a)


print(np.max(a))

print(np.max(a, axis=0))

print(np.max(a, axis=1))


[[0 1 2]
 [3 4 5]]
5
[3 4 5]
[2 5]


__argmax__ : Returns the indices of the maximum values along an axis

In [78]:
print(a)
print(np.argmax(a))

print(np.argmax(a, axis=0))

print(np.argmax(a, axis=1))


[[0 1 2]
 [3 4 5]]
5
[1 1 1]
[2 2]


__min__ : 

In [45]:
print(np.min(a))

print(np.min(a, axis=0))

print(np.min(a, axis=1))

0
[0 1 2]
[0 3]


__argmin__ : Returns the indices of the minimum values along an axis.



In [46]:
print(np.argmin(a))

print(np.argmin(a, axis=0))

print(np.argmin(a, axis=1))

0
[0 0 0]
[0 0]


__argwhere__ : Find the indices of array elements that are non-zero, grouped by element.



In [80]:
x = np.arange(6).reshape(2,3)

print(x)


np.argwhere(x>1)

[[0 1 2]
 [3 4 5]]


array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)