# Numby is the fastest list computaiton library

#vector --> multi dimentional arrays
#scalar --> single dimentional arrays




In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
arr=np.array(my_list)

In [4]:
arr.shape

(3,)

In [5]:
arr.reshape(3,1)

array([[1],
       [2],
       [3]])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
arr=np.array(my_matrix)

In [8]:
arr.reshape(1,9)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [10]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,10,)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(3)

array([0.42755112, 0.22914409, 0.47162146])

In [20]:
np.random.rand(5,5)

array([[0.45244812, 0.03695173, 0.08558078, 0.38282408, 0.88494016],
       [0.0056934 , 0.33107924, 0.14898177, 0.20856633, 0.05625883],
       [0.47189724, 0.99081835, 0.25855427, 0.93981383, 0.67000414],
       [0.7586487 , 0.08818959, 0.60397637, 0.09428279, 0.90750929],
       [0.38324461, 0.13642866, 0.77066747, 0.14444576, 0.78154937]])

In [22]:
np.random.randn(3,2)

array([[-2.49986677, -1.24434368],
       [ 0.2339608 , -0.21384337],
       [ 0.20588457,  1.00362549]])

In [27]:
ranarr=np.random.randint(1,100,10)

In [30]:
ranarr.max(),ranarr.min()

(81, 5)

In [31]:
ranarr.argmax()

0

In [32]:
arr = np.arange(0,11)

In [33]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [36]:
arr[0:5]=100

In [37]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr = np.arange(0,11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr = arr[0:6]

In [41]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
slice_of_arr[:]=99

In [46]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy=arr.copy()

In [49]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy[:]=200

In [51]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [53]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d[1,1]

25

In [56]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [61]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [67]:
arr_2d[:,-1:]

array([[15],
       [30],
       [45]])

In [72]:
arr_2d[1:,:1]

array([[20],
       [35]])

In [83]:
arr_2d[1:,[0,2]]

array([[20, 30],
       [35, 45]])

In [84]:
arr_2d[1:,::-2]

array([[30, 20],
       [45, 35]])

In [92]:
#5,15,35,45
arr_2d[::2,[0,2]]

array([[ 5, 15],
       [35, 45]])

In [93]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [97]:
bool_arr =arr >10

In [98]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99])

In [99]:
arr[arr>4]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [101]:
arr_cop-arr_2d

ValueError: operands could not be broadcast together with shapes (11,) (3,3) 

In [103]:
arr*3.0

array([297., 297., 297., 297., 297., 297.,  18.,  21.,  24.,  27.,  30.])

In [104]:
np.sqrt(arr)

array([9.94987437, 9.94987437, 9.94987437, 9.94987437, 9.94987437,
       9.94987437, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [105]:
np.exp(arr)

array([9.88903032e+42, 9.88903032e+42, 9.88903032e+42, 9.88903032e+42,
       9.88903032e+42, 9.88903032e+42, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [106]:
np.sin(arr)

array([-0.99920683, -0.99920683, -0.99920683, -0.99920683, -0.99920683,
       -0.99920683, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [108]:
np.log(arr)

array([4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985,
       4.59511985, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [109]:

import numpy as n

In [110]:
n.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
n.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [112]:
n.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [117]:
a=range(10,51)
n.array(a)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [119]:
a=range(10,51,2)

In [120]:
n.array(a)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [121]:
a=range(0,9)

In [125]:
b=n.array(a)

In [126]:
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
n.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
n.random.rand(1)

array([0.47433616])

In [138]:
n.random.randn(25)

array([-0.1611791 ,  1.20927755, -0.12717215, -1.00946577,  0.42544605,
       -0.36927833, -1.46179211,  0.54132683, -1.23929673,  0.01231114,
       -2.44753005,  2.05150689, -0.62209016, -0.73551309,  0.13573853,
        0.39782882,  0.51903809,  0.69500938, -0.70194981,  1.74868227,
        1.27171023,  0.7585482 ,  1.90196089, -1.18304778, -0.96490748])

In [148]:
n.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [150]:
n.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## numpy indexing selection

In [155]:
mat = n.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [156]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [159]:
mat[3,4]

20

In [164]:
mat[:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [165]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [167]:
mat[-2:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [169]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [170]:
#sum of all valus in mat
mat.sum()

325

In [171]:
mat.std()

7.211102550927978

In [172]:
mat.sum(0)

array([55, 60, 65, 70, 75])

In [173]:
mat.sum(1)

array([ 15,  40,  65,  90, 115])

## indexing and slicing


In [179]:
arr = n.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
