In [2]:
import numpy as np
from numpy.random import randint as ri

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [21]:
mat1 = np.array(ri(10,100,15)).reshape(3,5)
mat2 = np.array(ri(1,10,15)).reshape(3,5)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)

print("\nAddition\n------------------\n",mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)

print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n",3*mat1 - 2*mat2)

print("\nAddition of a scalar (100)\n-------------------------\n", mat1 + 100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", np.power(mat1,3))

print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.power(mat1,.5))
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.sqrt(mat1))


1st Matrix of random single-digit numbers
----------------------------------------
 [[80 89 74 34 74]
 [71 68 76 68 66]
 [41 78 81 53 32]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[1 3 6 2 7]
 [2 8 2 1 4]
 [8 8 3 5 1]]

Addition
------------------
 [[81 92 80 36 81]
 [73 76 78 69 70]
 [49 86 84 58 33]]

Multiplication
------------------
 [[ 80 267 444  68 518]
 [142 544 152  68 264]
 [328 624 243 265  32]]

Division
------------------
 [[80.         29.66666667 12.33333333 17.         10.57142857]
 [35.5         8.5        38.         68.         16.5       ]
 [ 5.125       9.75       27.         10.6        32.        ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[238 261 210  98 208]
 [209 188 224 202 190]
 [107 218 237 149  94]]

Addition of a scalar (100)
-------------------------
 [[180 189 174 134 174]
 [171 168 176 168 166]
 [141 178 181 153 132]]

Exponentiation, matrix cubed here
--------------------------------

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [3]:
from numpy.random import randint as ri
mat1 = np.array(np.random.randint(10,20,10)).reshape(2,5)
mat2 = np.array(np.random.randint(20,30,10)).reshape(5,2)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)

print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",mat1.sum(axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",mat1.sum(axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",)



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[17 16 19 12 15]
 [10 18 18 11 10]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[28 20]
 [25 25]
 [23 21]
 [25 29]
 [25 27]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 146

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [27 34 37 23 25]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [79 67]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 



### 4.Sort

In [41]:
A = np.random.randint(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [23 64 34 53 57 83 31 60 96 47]

Here is the sorted vector
 -------------------------------------------------- 
 [23 31 34 47 53 57 60 64 83 96]


In [49]:
M = np.array(ri(0,100,25)).reshape(5,5)
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[89 85 84 33 68]
 [62 95 34 96 53]
 [79 62 18 30 14]
 [28 32 67 52 27]
 [38 38 63 16 85]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[33 68 84 85 89]
 [34 53 62 95 96]
 [14 18 30 62 79]
 [27 28 32 52 67]
 [16 38 38 63 85]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[28 32 18 16 14]
 [38 38 34 30 27]
 [62 62 63 33 53]
 [79 85 67 52 68]
 [89 95 84 96 85]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [61]:
# Fill the following ***** with appropriate solution.
a=np.random.randint(0,10,2)
b=np.random.randint(0,10,3)
c=np.random.randint(0,10,4)

print("a:", a)
print("b:", b)
print("c:", c)

a: [4 7]
b: [1 3 0]
c: [8 3 7 9]


In [62]:
print("Max of a:", np.max(a) )
print("Max of b:", np.max(b) )


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Min of a:", np.min(a) )
print("Min of b:", np.min(b) )


print("Min of a location:", np.argmin(a))
print("Min of b location:", np.argmin(b))
print("Min of c location:", np.argmin(c))

Max of a: 7
Max of b: 3
Max of a location: 1
Max of b location: 1
Max of c location: 3


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [70]:
mat1 = np.array(np.random.randint(0,50,4)).reshape(2,2)
mat1

array([[ 9, 47],
       [37, 11]])

In [4]:

mat1 = np.array(np.random.randint(0,50,4)).reshape(2,2)
mat2 = np.array(np.random.randint(0,50,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n",np.sqrt(mat1) )


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n",np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,2))
np.mod


1st Matrix of random single-digit numbers
----------------------------------------
 [[ 5 20]
 [46 26]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[ 4 16 22]
 [33 37  3]
 [ 2 36 22]]

Sq-root of 1st matrix using np
------------------
 [[2.23606798 4.47213595]
 [6.78232998 5.09901951]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.48413159e+02 4.85165195e+08]
 [9.49611942e+19 1.95729609e+11]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    1.30103   ]
 [1.66275783 1.41497335]]

Modulo reminder using np
 -------------------------------------------------- 
 [[1 0]
 [0 0]]


<ufunc 'remainder'>

### 7.Generating matrices from distributions

In [20]:
print("Random number generation (from Uniform distribution)")
a = np.array(np.random.random(6)).reshape(2,3)
a

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
np.random.normal()
print(np.random.normal())

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

print(np.random.randint(1,100,(12,3))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
0.6768578435545487
Random integer vector: [39  8 63 94 98 70 79 28  7 84]

Random integer matrix
[[51 28 53]
 [82 47 17]
 [52 99  7]
 [78 39  9]
 [72 83 69]
 [66 90 47]
 [ 4  7 93]
 [28 21  8]
 [52 66 47]
 [95 57 72]
 [54 38 60]
 [64 79 11]]

20 samples drawn from a dice throw: [2 5 6 5 6 6 2 6 1 3 4 1 1 2 3 6 2 3 5 6]


### 8.Find the nearest value from a given number in an array using NumPy.

In [33]:
b = np.random.uniform(1,13,5)
print(b)
type(b)
v = 12
n = b[np.abs(b - v).argmin()]
print(n)

[ 4.02972422 11.33316708  9.00474545  1.6831814   6.28869801]
11.333167079743113


In [21]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

4.859577122593637


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]