In [ ]:
import numpy as np

### 1. Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [ ]:
mat1 = np.array(np.random.randint(1,10,9)).reshape(3,3)
mat2 = np.array(np.random.randint(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

### 2. Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [ ]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))


###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [5]:
##Solution
import numpy as np
from numpy.random import randint as ri
mat1 = np.array(ri(1,100,9)).reshape(9,1)
mat1

array([[42],
       [98],
       [46],
       [ 8],
       [75],
       [11],
       [17],
       [12],
       [ 5]])

### 4. Sort

In [6]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))


Vector of random integers
 -------------------------------------------------- 
 [34  2 66 42 75  4 73 72 60 10]

Here is the sorted vector
 -------------------------------------------------- 
 [ 2  4 10 34 42 60 66 72 73 75]


In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))

### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [3]:
from numpy.random import randint as ri
a=ri(1,100,10)
b=ri(5,50,10)
c=ri(7,200,10)
print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:", b.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

print("Max of a:", a.min())
print("Max of b:", b.min())


print("Max of a location:", a.argmin())
print("Max of b location:", b.argmin())
print("Max of c location:", b.argmin())



a: [45  9 51 87 50 93 14 74 76 89]
b: [29 32 45 29 45  5 26 24 46 30]
c: [ 64 110  29 117 119 191  68  67  44  18]
Max of a: 93
Max of b: 46
Max of a location: 5
Max of b location: 8
Max of c location: 8
Max of a: 9
Max of b: 5
Max of a location: 1
Max of b location: 5
Max of c location: 5


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))


### 7.Generating matrices from distributions

In [5]:
import numpy as np
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.65632846 0.72030634 0.33893315]
 [0.09517165 0.0438688  0.72737685]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.19057942 -0.16628382  0.79308919]
 [-0.9255194  -1.19475391  0.02234534]
 [-0.54122854  1.80650062  0.74789428]
 [-1.56922059  0.03341957 -2.18367473]]
Random integer vector: [41 78 62 52 15 38 33 75 17 17]

Random integer matrix
[[79 63 22 63]
 [71 99 34 78]
 [45 11 81 22]
 [81 79 60 40]]

20 samples drawn from a dice throw: [4 6 2 5 3 1 3 5 2 4 6 6 5 4 5 3 1 1 4 2]


### 8.Find the nearest value from a given number in an array using NumPy.

In [12]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

import numpy as np
x = np.random.uniform(1, 12, 5)
print("\nInput array\n","-"*50,"\n",x)
v = 4
n = x[np.abs(x - v).argmin()]
print(n)


Input array
 -------------------------------------------------- 
 [1.96218901 6.52211028 4.58153057 6.72010105 8.97825055]
4.581530572165068


In [11]:
x.flat[3]

10.831083801962587

#### 9. Write code using numpy to produce following output
* [[0 0 0]
 [0 1 2]
 [0 2 4]]

In [ ]:
import numpy as np
print(np.fromfunction(lambda i, j: i*j, (3, 3), dtype=int))